### ISSUE TITLE
Question: Is this library compatible with PySpark?

### ISSUE THREAD

**Issue by leovegas** [IBM/spark-s3-shuffle#82]
Seeing following stacktrace:

2023-10-04 16:20:12.803 | 23/10/04 14:20:12 INFO SparkContext: Successfully stopped SparkContext |  
  |   | 2023-10-04 16:20:12.799 | 23/10/04 14:20:12 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped! |  
  |   | 2023-10-04 16:20:12.796 | 23/10/04 14:20:12 INFO BlockManagerMaster: BlockManagerMaster stopped |  
  |   | 2023-10-04 16:20:12.790 | 23/10/04 14:20:12 INFO BlockManager: BlockManager stopped |  
  |   | 2023-10-04 16:20:12.790 | 23/10/04 14:20:12 INFO MemoryStore: MemoryStore cleared |  
  |   | 2023-10-04 16:20:12.776 | 23/10/04 14:20:12 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped! |  
  |   | 2023-10-04 16:20:11.927 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.checksum.enabled=true |  
  |   | 2023-10-04 16:20:11.927 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.checksum.algorithm=ADLER32 |  
  |   | 2023-10-04 16:20:11.927 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.forceBatchFetch=false (default: false) |  
  |   | 2023-10-04 16:20:11.927 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.useBlockManager=true (default: true) |  
  |   | 2023-10-04 16:20:11.925 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.alwaysCreateIndex=false (default: false) |  
  |   | 2023-10-04 16:20:11.925 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.folderPrefixes=10 |  
  |   | 2023-10-04 16:20:11.925 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.cleanup=true |  
  |   | 2023-10-04 16:20:11.924 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.cacheChecksums=true |  
  |   | 2023-10-04 16:20:11.924 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.cachePartitionLengths=true |  
  |   | 2023-10-04 16:20:11.923 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.maxConcurrencyTask=10 |  
  |   | 2023-10-04 16:20:11.922 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.maxBufferSizeTask=134217728 |  
  |   | 2023-10-04 16:20:11.922 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.bufferSize=8388608 |  
  |   | 2023-10-04 16:20:11.922 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.useSparkShuffleFetch=false
2023-10-04 16:20:11.921 | 23/10/04 14:20:11 INFO S3ShuffleDispatcher: - spark.shuffle.s3.rootDir

at java.base/java.lang.Thread.run(Thread.java:833) 

  |   | 2023-10-04 16:20:11.424 | at py4j.ClientServerConnection.run(ClientServerConnection.java:106) |  
  |   | 2023-10-04 16:20:11.424 | at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182) |  
  |   | 2023-10-04 16:20:11.424 | at py4j.commands.CallCommand.execute(CallCommand.java:79) |  
  |   | 2023-10-04 16:20:11.424 | at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) |  
  |   | 2023-10-04 16:20:11.424 | at py4j.Gateway.invoke(Gateway.java:282) |  
  |   | 2023-10-04 16:20:11.424 | at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357) |  
  |   | 2023-10-04 16:20:11.424 | at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:185) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210) |  
  |   | 2023-10-04 16:20:11.424 | at scala.Option.getOrElse(Option.scala:189) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:411) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:207) |  
  |   | 2023-10-04 16:20:11.424 | at scala.Option.orElse(Option.scala:447) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:210) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.inferSchema(ParquetFileFormat.scala:168) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.execution.datasources.parquet.ParquetUtils$.inferSchema(ParquetUtils.scala:125) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.mergeSchemasInParallel(ParquetFileFormat.scala:526) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.mergeSchemasInParallel(SchemaMergeUtils.scala:70) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.rdd.RDD.collect(RDD.scala:1020) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.rdd.RDD.withScope(RDD.scala:406) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1021) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.SparkContext.runJob(SparkContext.scala:2293) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.SparkContext.runJob(SparkContext.scala:2268) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.SparkContext.runJob(SparkContext.scala:2249) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.SparkContext.runJob(SparkContext.scala:2228) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:952) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/java.lang.Thread.run(Thread.java:833) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) |  
  |   | 2023-10-04 16:20:11.424 | at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.util.SparkShutdownHookManager$anon$2.run(ShutdownHookManager.scala:178) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188) |  
  |   | 2023-10-04 16:20:11.424 | at scala.util.Try$.apply(Try.scala:213) |  
  |   | 2023-10-04 16:20:11.424 | at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$1(ShutdownHookManager.scala:188) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066) |  
  |   | 2023-10-04 16:20:11.424 | at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$2(ShutdownHookManager.scala:188) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:214) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.SparkContext.$anonfun$new$35(SparkContext.scala:660) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.SparkContext.stop(SparkContext.scala:2095) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1484) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.SparkContext.$anonfun$stop$11(SparkContext.scala:2095) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:2784) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.util.EventLoop.stop(EventLoop.scala:84) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:2887) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:1186) |  
  |   | 2023-10-04 16:20:11.424 | at scala.collection.mutable.HashSet.foreach(HashSet.scala:79) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.scheduler.DAGScheduler.$anonfun$cleanUpAfterSchedulerStop$1$adapted(DAGScheduler.scala:1186) |  
  |   | 2023-10-04 16:20:11.424 | at org.apache.spark.scheduler.DAGScheduler.$anonfun$cleanUpAfterSchedulerStop$1(DAGScheduler.scala:1188) |  
  |   | 2023-10-04 16:20:11.424 | : org.apache.spark.SparkException: Job 0 cancelled because SparkContext was shut down

**Comment by leovegas** [comment]
Actually pyspark app works with 1 executor
But as soon as we increase number of executors (>1), we get same error.

**Comment by leovegas** [comment]
It works with dynamicAllocation.
